spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wetech_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Tengsk123
    hikari:
        max-lifetime: 1000000
